---
server:
  port: 3001

spring:
  profiles:
    active: dev
---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: ${env.MONGO_DATABASE}
      uri: mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}